feat(bootloader): can bringup
Opentrons/ot3-firmware pull request #216
Opened 2022-01-24 21:41 UTC by amitlissack

2022-01-25 14:24 UTC, sfoster1 requested changes
Ugh I should have seen this in the last PR, sorry, but IMO we want to reserve a node id bit or some other bit somewhere for whether a node is in bootloader state or application state, that's in the get device info response somewhere. That way it's easy to tell from the get device info response whether this is a bootloader or not while keeping the device info generic, and I think it's just good practice to consider those separate planes of control. 

We could make this part of the node ID; we could also change our arbitration ID slicing to take one of the bits that used to be the group code or something and make it the bootloader bit.

Other than that, does look good.

2022-01-25 15:22 UTC, amitlissack commented
> Ugh I should have seen this in the last PR, sorry, but IMO we want to reserve a node id bit or some other bit somewhere for whether a node is in bootloader state or application state, that's in the get device info response somewhere. That way it's easy to tell from the get device info response whether this is a bootloader or not while keeping the device info generic, and I think it's just good practice to consider those separate planes of control.
> 
> We could make this part of the node ID; we could also change our arbitration ID slicing to take one of the bits that used to be the group code or something and make it the bootloader bit.
> 
> Other than that, does look good.

Sounds wise.

2022-01-26 14:25 UTC, sfoster1 approved these changes
Nice! Looks good

2022-01-26 14:25 UTC, sfoster1 commented on python/opentrons_ot3_firmware/constants.py
> +@unique
didn't know about this, that's cool

2022-01-26 15:57 UTC, merged