Enable data ready
Opentrons/ot3-firmware pull request #378
Opened 2022-05-31 19:19 UTC by caila-marashaj

2022-06-01 13:04 UTC, sfoster1 commented on include/sensors/firmware/sensor_hardware.hpp
> +    auto check_data_ready() -> void override {
```suggestion
    auto check_data_ready() -> bool override {
```

2022-06-01 13:04 UTC, sfoster1 commented on include/sensors/firmware/sensor_hardware.hpp
> +        gpio::is_set(hardware.data_ready);
```suggestion
        return gpio::is_set(hardware.data_ready);
```

2022-06-01 13:05 UTC, sfoster1 commented on include/sensors/firmware/sensor_hardware.hpp
> +    auto set_sync_in() -> void override { gpio::set(hardware.sync_in); }
Yeah these absolutely need to be `sync_out` not `sync_in` - `sync_in` is the one you read, and `sync_out` is the one you write

2022-06-01 13:06 UTC, sfoster1 commented on pipettes/firmware/main.cpp
> +struct motion_controller::HardwareConfig plunger_pins {
Should this be here? Did it move from somewhere? If so, where did it move from?

2022-06-01 14:26 UTC, Laura-Danielle requested changes
Overall structure looks good. Seems like you aren't actually using the data ready pin in the pressure driver yet though?

2022-06-01 14:26 UTC, Laura-Danielle commented on include/pipettes/core/interfaces.hpp
> +auto sensor_configurations<PipetteType::SINGLE_CHANNEL>()
Mind grouping the generic and specific templates next to each other for readability purposes?

2022-06-01 14:26 UTC, Laura-Danielle commented on include/sensors/core/sensor_hardware_interface.hpp
> +    virtual auto set_sync_out() -> void = 0;
I think you can keep this as 'set_sync'

2022-06-01 14:26 UTC, Laura-Danielle commented on include/sensors/core/tasks/pressure_driver.hpp
> +          hardware(hardware),
Are you planning on using the data ready pin in a follow-up PR? Otherwise, right now it's not being used.

2022-06-02 13:28 UTC, sfoster1 requested changes
Couple small things that need to change - specifically around the 8 channels and the way pins are specifically set in the high throughputs - but looking good!

2022-06-02 14:28 UTC, caila-marashaj commented on CMakeLists.txt
> +        ./eeprom/*.hpp ./eeprom/*.cpp
I believe from a rebase- I seemed to pick up some random eeprom changes along the way. Taking this out of my branch though

2022-06-02 20:34 UTC, merged