Enable data ready fix
Opentrons/ot3-firmware pull request #384
Opened 2022-06-02 21:02 UTC by caila-marashaj

This pr adds hardware support for the data ready pins on the pipette main boards, but does not check that pin's value or incorporate it into the pressure sensor reads. That will be done in a follow-up pr.

2022-06-02 21:24 UTC, sfoster1 approved these changes
I'm good with this as long as you smoke test it.

2022-06-03 14:28 UTC, Laura-Danielle approved these changes
Two changes that you can get rid of b/c they're unused, but otherwise looks good to merge.

2022-06-03 14:28 UTC, Laura-Danielle commented on pipettes/firmware/hardware_config.h
> +    pipette_hardware_device_sync_out,
I think this is not a needed change.

2022-06-03 14:28 UTC, Laura-Danielle commented on pipettes/firmware/hardware_config.c
> -
same here

2022-06-03 17:46 UTC, Laura-Danielle requested changes

2022-06-03 17:46 UTC, Laura-Danielle commented on pipettes/firmware/hardware_config.c
> +        case pipette_hardware_device_data_ready:
This is the wrong function. It should be in `get_gpio_lt`

2022-06-03 17:46 UTC, Laura-Danielle commented on pipettes/firmware/hardware_config.h
> +    pipette_hardware_device_sync_out,
Resolving: It is being used, but it wasn't implemented in `hardware_config.c`

2022-06-03 17:57 UTC, Laura-Danielle approved these changes

2022-06-03 18:24 UTC, merged