refactor(tmc2160): modify how we scale current on the tmc2160 motor driver
Opentrons/ot3-firmware pull request #391
Opened 2022-06-16 20:02 UTC by Laura-Danielle

## Overview

The datasheet for the 2160 driver suggests that current be scaled based on the global scalar as
opposed to calculated the value of IRUN Or IHOLD directly. I think we probably need to dig a bit
deeper into stealthchop, whenever we want to actually configure it properly, because there were some
warnings around changing the global scalar while using this feature.

2022-06-16 20:04 UTC, sfoster1 commented on include/motor-control/core/stepper_motor/tmc2160.hpp
> +    auto check_operational_value() -> void {
if this changes the value, we should call this `clamp_value` or something

2022-06-16 20:31 UTC, Laura-Danielle commented on include/motor-control/core/stepper_motor/tmc2160.hpp
> +        if (global_scaler != 0) {
You mean why not set it to zero?

2022-06-21 14:00 UTC, sfoster1 requested changes
Looks good but that comment's gotta change. Also the clamp logic makes sense to me - hadn't realized that 0 was a magic fullscale value

2022-06-21 14:50 UTC, sfoster1 approved these changes
Looks good to me!

2022-06-21 14:55 UTC, merged