polling for pressure sensor
Opentrons/ot3-firmware pull request #416
Opened 2022-07-21 19:42 UTC by caila-marashaj

2022-07-25 18:03 UTC, Laura-Danielle requested changes
A few comments to cleanup stuff. Main thing is to add that additional test w/ multiple different types of read calls in it.

2022-07-25 18:03 UTC, Laura-Danielle commented on sensors/tests/test_pressure_driver.cpp
> +    GIVEN("Pressure read with output binding = report") {
Can we also do a multi-tier call test? What I mean by that would be, in the same `GIVEN` call:

1. Do a limited poll call
2. Do a single read
3. Do a continuous poll call
4. Do another single read call

2022-07-25 18:13 UTC, caila-marashaj commented on include/sensors/core/tasks/pressure_driver.hpp
> +        stop_polling = ((static_cast<uint8_t>(binding) & 0x3) == 0x0);
believe so- because we want to make sure that neither of the two lsb are set before we stop measuring completely

2022-07-25 18:23 UTC, sfoster1 requested changes
Agree with @Laura-Danielle and also think that we need to be doing comparisons to enum elements, not to numeric literals of what's behind the enum elements.

2022-07-25 18:23 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +        stop_polling = ((static_cast<uint8_t>(binding) & 0x3) == 0x0);
I would do bitwise comparisons directly. Maybe put it in a helper function that does `(binding & SensorOutputBinding::sync) || (binding & SensorOutputBinding::report)` or something. If you really want to keep this as a mask, definitely put it in a function and make the mask a constexpr variable defined from the enum, like `constexpr uint8_t BINDING_MASK = static_cast<uint8_t>(SensorOutputBinding::sync) | static_cast<uint8_t>(SensorOutputBinding::report)`.

2022-07-25 18:23 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +        report = ((static_cast<uint8_t>(binding) & 0x2) == 0x2);
these similarly should be helper functions and they should compare to the actual enum values casted into uint8_ts, not literals of the underlying values.

2022-07-28 21:04 UTC, sfoster1 approved these changes
looks good to me!

2022-07-29 13:45 UTC, Laura-Danielle approved these changes
Tests look good and such. I think you just missed one comment from my previous review that needs to be addressed.

2022-07-29 13:45 UTC, Laura-Danielle commented on include/sensors/core/tasks/pressure_sensor_task.hpp
> +            driver.set_limited_poll(true);
@caila-marashaj think you missed this comment. We still want to make sure we set # of reads to 1 here

2022-08-01 17:01 UTC, merged