fix(pipettes): unlimited polling bug fix
Opentrons/ot3-firmware pull request #494
Opened 2022-11-09 16:26 UTC by caila-marashaj

Fix for unlimited polling on the pressure sensor- this allows us to read continuously from `monitor_sensors.py` or `can_control.py`. 

Moves pressure conversion from `send_pressure` to `handle_response`, and compares the threshold value to this converted pressure

**Note:**
The threshold is set very high right now and will need to be changed after we test and determine what an appropriate value would be.

2022-11-10 19:04 UTC, Laura-Danielle commented on include/sensors/core/tasks/pressure_driver.hpp
> +    int32_t threshold_cmH20 = 0x0FFFFFFF;
wait don't we want this to be a float rather than it being fixed point?

2022-11-11 14:05 UTC, fsinapi approved these changes
This LGTM!

2022-11-11 14:37 UTC, Laura-Danielle requested changes
- Seems like there is some weird rebasing
- I _think_ it might be better to do the comparison using floats (I can make this change next week)

2022-11-11 16:13 UTC, Laura-Danielle approved these changes
One comment about the threshold, but otherwise looks good to me

2022-11-11 16:22 UTC, fsinapi commented on include/sensors/core/tasks/pressure_driver.hpp
> +    float threshold_cmH20 = 2457.0F;
I'll throw a comment in here

2022-11-11 16:25 UTC, laviera commented
@fsinapi @Laura-Danielle - is this PR ready to be merged ?

2022-11-11 16:31 UTC, merged