fix(pipettes): change comparison to pascals
Opentrons/ot3-firmware pull request #522
Opened 2022-12-08 21:37 UTC by caila-marashaj

This code changes the comparison for reaching a threshold from cm of water to pascals. It converts the pressure reading from the sensor to pascals, and then does the comparison to the threshold value.

A couple possible concerns though:
  - this assumes the threshold sent from Python is in Pascals
  - this code now leaves the value stored in `_registers.pressure.reading` unused, and instead uses the value stored in the private variable in `pressure_pascals`

2022-12-09 14:35 UTC, sfoster1 approved these changes
I think this is fine, because
- yes, you have to get the units right. let's document that
- we do actually store the data in the register, we're just not using it at least right now

2022-12-12 21:54 UTC, Laura-Danielle requested changes
In general, I agree with the change. Have two tiny requests and then I will approve.

2022-12-12 21:54 UTC, Laura-Danielle commented on include/sensors/core/tasks/pressure_driver.hpp
> +    float pressure_pascals = 0.0F;
I don't think we should have this be a private variable on the pressure driver class.

2022-12-12 21:54 UTC, Laura-Danielle commented on include/sensors/core/tasks/pressure_driver.hpp
> +            convert_to_fixed_point(pressure_pascals, S15Q16_RADIX);
can we put some comments in the send pressure functions that we are sending over pascals? We should probably also document [this in confluence](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/3513712720/Pressure+Sensor).

2022-12-14 20:28 UTC, Laura-Danielle approved these changes
lgtm

2022-12-15 14:56 UTC, merged