feat(pipettes): add GPIO EXTI interrupt support for the tip sense GPIOs
Opentrons/ot3-firmware pull request #601
Opened 2023-03-15 21:58 UTC by Laura-Danielle

## Overview

We want to decide that a tip has been detected based on an EXTI interrupt. This PR adds the piping in HAL to support an EXTI interrupt. While making these changes, I also edited the code on the pressure sensor to support two data ready lines for the 96 channel. We'll also want to do this for DVT 8 channel pipettes since there are now two separate data ready lines.

## Test Plan

- [ ] Test that the pressure sensor still functions normally on the single/eight channel

2023-03-16 13:43 UTC, fsinapi requested changes
Had a few comments but the big one is how `get_interrupt_line_ht` tries to return two different IRQ lines, I'm pretty sure we're going to have to use a different approach there.

2023-03-16 13:43 UTC, fsinapi commented on pipettes/firmware/utility_gpio.c
> +        // /* EXTI interrupt init*/
Guessing this should be uncommented before merging?

2023-03-16 13:43 UTC, fsinapi commented on pipettes/firmware/stm32g4xx_it.c
> +    EXTI->PR1 = EXTI_LINE_2;
Similar to checking `PR1`, can we clear using `__HAL_GPIO_EXTI_CLEAR_FLAG`?

2023-03-16 13:43 UTC, fsinapi commented on pipettes/firmware/hardware_config.c
> +            return EXTI15_10_IRQn | EXTI9_5_IRQn;
I don't think that this is going to give you the behavior you want. The `IRQn` enums are not single-bit values, but instead indices into the NVIC bitfields. Returning two IRQn values OR'd together is probably going to end up enabling a completely different IRQ.

2023-03-16 15:45 UTC, Laura-Danielle commented
Yeah I needed to test this on the firmware to see if that would actually work. I know you can combine GPIOs but it wasn't clear to me in the NVIC documentation whether the same thing would work or not. I can just change the implementation (and probably make the code more readable by doing so.)

2023-03-16 18:05 UTC, sfoster1 approved these changes
Looks good to me!

2023-03-16 18:46 UTC, caila-marashaj approved these changes
Exciting!!

2023-03-17 20:26 UTC, Laura-Danielle commented
Tested liquid sensing, auto calibration and the new tip sense functionality on a robot. Everything is functioning as expected ✔️

2023-03-17 20:35 UTC, merged