refactor(motor-control): add GPIO config file in each individual subsystem
Opentrons/ot3-firmware pull request #63
Opened 2021-08-12 15:02 UTC by ahiuchingau

We can now configure each subsystem with a unique set of GPIO pins for motor control.

2021-08-12 16:01 UTC, sfoster1 requested changes
Let's not introduce more header-definition based configuration. We already have some that we have to use because of other people's code, but let's not add more.

Instead, we should define a struct that holds the configuration so that it can be passed at runtime. As long as we declare the port as a pointer, we can forward-declare it to C and be just fine without having to include the device header; and then the pin is just a number.

There's two or three basic ways we could handle this struct:
- We could have an API like this, with set-direction/set-step/etc, which takes as its arguments the port and pin. This would be the quickest method but it might provide for some programmer error since you could accidentally pass the step pin into set_direction.
- We could have an API that looks more like just set and reset, which takes as its arguments the port and pin; this would be more general. It would look basically exactly like that HAL class, and would probably get eliminated by the compiler, but would continue to serve the purpose of avoiding including the hal headers in the c++
- We could make this C interface into an object. What we'd do here is we'd take that struct and make these set_direction/set_step/etc functions take a pointer to that struct as their first argument; the firmware layer for the end executable would create it, pass it into the c++ motor controller, and that would hold it by-value and pass it down to the c calls. We could even take this a step further and store pointers to these functions in the struct, but that's kind of nasty.

Either way, let's not do this configuration via #define.

2021-08-16 18:23 UTC, amitlissack commented on common/firmware/motor_driver/motor.c
> +void Set_Step() { HAL_GPIO_WritePin(STEP_GPIO_PORT, STEP_PIN, GPIO_PIN_SET); }
Minor point, but we use snake case for function names. Lower case.

2021-08-18 20:36 UTC, sfoster1 approved these changes
Nice! this is pretty much what we were thinking about. One commented include to remove though.

2021-08-18 20:36 UTC, sfoster1 commented on pipettes/firmware/uart_task.cpp
> +//#include "pipettes/firmware/hardware_config.hpp"
remove

2021-08-18 20:55 UTC, ahiuchingau commented on pipettes/firmware/uart_task.cpp
> +//#include "pipettes/firmware/hardware_config.hpp"
Oh man!

2021-08-18 21:05 UTC, merged