add acceleration to TipActionRequest message
Opentrons/ot3-firmware pull request #653
Opened 2023-05-03 15:10 UTC by caila-marashaj

2023-05-03 21:11 UTC, Laura-Danielle requested changes
You need to edit:

`include/motor-control/core/stepper-motor/motion_controller.hpp::PipetteMotionController`

in order for the acceleration to actually get used (and I believe the pip motion controller task too).

Let me know if you can't find where these are.

2023-05-04 18:53 UTC, Laura-Danielle approved these changes
yep looks good, but please don't merge in till the python pr is ready to be merged in.

2023-05-05 13:35 UTC, sfoster1 requested changes
_just in case_ so we don't drive ourselves crazy if we flash the wrong thing, can we put the acceleration part at the end of the message and set it to 0 if we don't have a long enough message to include it

2023-05-05 13:35 UTC, sfoster1 commented
Looks good otherwise though!

2023-05-16 21:00 UTC, Laura-Danielle approved these changes

2023-07-26 16:11 UTC, ahiuchingau commented on include/can/core/messages.hpp
> +using UpdateGearMotorPositionEstimationRequest =
I don't understand what we're using to update gear motor position estimation? I don't think we have encoders on the tip motors, right?

2023-07-26 20:02 UTC, sfoster1 approved these changes
Looks good to me! Really great work.

2023-07-27 16:34 UTC, merged