feat(sensors): support new pipette sensor board
Opentrons/ot3-firmware pull request #797
Opened 2024-07-23 16:50 UTC by ryanthecoder

The new sensor board adds a GPIO expander so that we can read the version of the board and adjust how we read the pressure sensor.

The way this works is that there is a SensorHardwareVersionSingleton that is in charge of holding the version of the board, and it defaults to the version before we had the ability to see the sensor board rev. This singleton is then shared via the SensorHardwareBase instance(s) and a new ReadBoardRevTask

The new task attempts to query the i2c bus at the address of our expander, if it receives a response it compares the bitmap to known versions and sets the version of the singleton.

Now any sensor that gets updated, can change their behavior by asking their SensorHardware instance what rev to use instead of relying on compiler defines.

2024-07-23 18:53 UTC, sfoster1 requested changes
It looks good but there's a typo in the new class... it'll bother me forever if we don't change it.

Also can we add some way for the pipette to tell the host which sensor board it's got?

2024-07-23 18:53 UTC, sfoster1 commented on include/sensors/core/tasks/read_sensor_board_rev_task.hpp
> +        auto handler = ReadSenorBoardHandler(writer, get_queue());
```suggestion
        auto handler = ReadSensorBoardHandler(writer, get_queue());
```

2024-07-23 18:53 UTC, sfoster1 commented on include/sensors/core/tasks/read_sensor_board_rev_task.hpp
> +class ReadSenorBoardTask {
```suggestion
class ReadSensorBoardTask {
```
etc

2024-07-24 20:19 UTC, ryanthecoder commented
Tested Side by side with an old pipette and performing as expected

2024-07-24 20:20 UTC, sfoster1 approved these changes
Nice!

2024-07-24 20:50 UTC, merged