feat(sensors): add a new can message to batch read sensor data
Opentrons/ot3-firmware pull request #805
Opened 2024-09-27 15:52 UTC by ryanthecoder

In a first step to streamline tool_sensors.py we want to batch read sensor data, this will speed up the process and let us stream alot better

2024-09-27 17:07 UTC, caila-marashaj approved these changes
logic looks good to me!

2024-09-30 13:21 UTC, sfoster1 requested changes
Couple small readability and robustness changes and also definitely want some tests for the index math and logic

2024-09-30 13:21 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +            can_client.send_can_message(can::ids::NodeId::host, response);
We haven't faced it before as much, but I think we can improve this a lot by changing (or adding a new version of) `send_can_message` that will either (a) block (by sleeping) or (b) return `false` when the local buffer is full. That will let us dynamically slow down data output when the buffer is full while not adding a delay all the time.

2024-09-30 13:21 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +            while (j < 14 and i < count) {
We absolutely need some tests for the fiddly index math.

2024-09-30 13:21 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +        while (i < count) {
could make this `for(size_t i = 0; i < count; ) { }` if we wanted. in general, seems like we could use a size here instead of a signed value.

2024-09-30 13:21 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +        std::array<uint32_t, 14> data{};
would love to see this 14 derived from somewhere

2024-09-30 13:21 UTC, sfoster1 commented on include/sensors/core/tasks/pressure_driver.hpp
> +            while (j < 14 and i < count) {
also can use `j < data.size()` or even take this to a range-for that stops early a la
```c++
for (auto& copy_to : data) {
    if (i >= count) {
        break;
    }
    copy_to = mmr920::reading_to_fixed_point(sensor_buffer->at(current_index));
    i++;
    current_index = (i + start) % static_cast<int>(SENSOR_BUFFER_SIZE);
}
```

2024-09-30 18:41 UTC, ryanthecoder commented
Marking as draft since Caila didn't get a chance to use this before her trip. I'll clean it up and make it better styled

2024-10-16 16:35 UTC, sfoster1 approved these changes
Nice, looks good to me!

2024-10-16 17:17 UTC, merged